### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

### ISSUE THREAD

**Issue by patilaum** [ncbi-nlp/BioSentVec#10]
Unable to import BioWord2Vec with KeyedVectors. Also tried with Word2Vec. Then it is giving deprecation warnings. Please help as soon as possible.

**Comment by qingyu-qc** [comment]
Hi,

Can you please detail how you loaded the word embeddings and the related methods and parameters?

For BioWord2Vec, as we have summarized in Wiki, you can use the following:

from gensim.models import KeyedVectors
model = KeyedVectors.load_word2vec_format(filename, binary=True)

If you cannot import BioWord2Vec or Word2Vec, I assume that there are some errors in your method calling.

Thanks

**Comment by nfrn** [comment]
Hello,
First, I want to thank you for sharing your work,
I'm having the same issue, with ginsim version 0.3.4 and python 3.6.
Thank you,

![image](https://user-images.githubusercontent.com/11446113/54883582-b4e04600-4e5e-11e9-84f0-18051a4e21cb.png)


![image](https://user-images.githubusercontent.com/11446113/54883540-5b781700-4e5e-11e9-809b-6a20dac64934.png)

**Comment by qingyu-qc** [comment]
Hi,

I noticed that you were using the sentence embedding but imported using
word2vec. Please use sent2vec to import the sentence embedding as mentioned
in FAQ:

import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model('model.bin')
emb = model.embed_sentence("once upon a time .")
embs = model.embed_sentences(["first sentence .", "another sentence"])

You need to install sent2vec first.

Thanks!

**Comment by qingyu-qc** [comment]
Close for now. Let us know if you have questions.
