### ISSUE TITLE
Inconsistent window size

### ISSUE THREAD

**Issue by michelole** [ncbi-nlp/BioSentVec#14]
While both the paper and the [README.md](https://github.com/ncbi-nlp/BioSentVec/blob/master/README.md#biowordvec-1-biomedical-word-embeddings-with-fasttext) file mention window size of 20, the [train_biowordvec.sh](https://github.com/ncbi-nlp/BioSentVec/blob/master/src/train_biowordvec.sh) script uses `-ws 30`.

What was the final window size used to produce the models?

**Comment by qingyu-qc** [comment]
Hi,

Thanks for pointing out. The final window size was 20; the script just contains the values that we tried.

Thanks!
