### ISSUE TITLE
How to import sent2vec

### ISSUE THREAD

**Issue by rv-ltran** [ncbi-nlp/BioSentVec#16]
I want to use the pretrained BioSentVec to extract sentence vector. I am following the following codes and ran into the error: "no module named 'sent2vec'". Do you know how to resolve this?

import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model('model.bin')
emb = model.embed_sentence("once upon a time .") 

I have done the following steps:
- download the pretrained model BioSentVec: BioSentVec_PubMed_MIMICIII-bigram_d700.bin
- installed fasttext as below (fasttext was installed successfully)
$ wget https://github.com/facebookresearch/fastText/archive/v0.9.1.zip
$ unzip v0.9.1.zip
$ cd fastText-0.9.1
$ make
$pip install .

**Comment by yfpeng** [comment]
Sent2vec  can be installed from https://github.com/epfml/sent2vec

**Comment by qingyu-qc** [comment]
Close for now. Let us know if you have other problems. Thanks.

**Comment by preethyvarma** [comment]
Could you please let me know how you resolved it. I am facing the same issue

**Comment by kaushikacharya** [comment]
> Could you please let me know how you resolved it. I am facing the same issue

@preethyvarma 
Follow the steps:

1. Build fasttext as mentioned in https://github.com/facebookresearch/fastText#building-fasttext
2. Install sent2vec as explained in https://github.com/epfml/sent2vec

**Comment by arindam-halder** [comment]
Hello, I am getting the same attribute error. I am using pycharm to run the code. I but fasttext as well as sent2vec using the steps above. Also tried installing them via pycharm. Neither worked for me.

**Comment by Stannislav** [comment]
Note that if you install `sent2vec` using
```bash
$ pip install sent2vec
```
then you'll get the wrong package. This is because the package `sent2vec` [on PyPI](https://pypi.org/project/sent2vec/) is a [totally different package with the same name](https://github.com/pdrm83/sent2vec).

The correct way of installing `sent2vec` is to clone their repository here https://github.com/epfml/sent2vec and to follow the instructions in the README file

**Comment by swatisaivarma** [comment]
Can you please mention exactly how to import sent2vec from this location https://github.com/epfml/sent2vec? I have cloned the repo, but when I try to run it doesnt.

**Comment by AmmarFahmy** [comment]
> Can you please mention exactly how to import sent2vec from this location https://github.com/epfml/sent2vec? I have cloned the repo, but when I try to run it doesn't.

follow these steps, 
1. run command **conda activate (type your environment name)**
2. run command **git clone https://github.com/facebookresearch/fastText.git**
3. run command **cd fastText** 
4. run command **pip install .**
5. run command **cd ..**
6. run command **git clone https://github.com/epfml/sent2vec.git**
7. run command **cd sent2vec**
8. run command **pip install .**

you are done installing

**Comment by mvd-lab** [comment]
I tried @AmmarFahmy suggestion, but here is the error message I get. Help?

(searchenv) $ pip install .
Processing /Users/devarmu1/Progs/kg/ctkg_09092022/src/expwiths2v/sent2vec
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Cython>=0.29.13 in /Users/devarmu1/opt/anaconda3/envs/searchenv/lib/python3.9/site-packages (from sent2vec==0.0.0) (0.29.28)
Requirement already satisfied: numpy>=1.17.1 in /Users/devarmu1/opt/anaconda3/envs/searchenv/lib/python3.9/site-packages (from sent2vec==0.0.0) (1.22.3)
Building wheels for collected packages: sent2vec
  Building wheel for sent2vec (pyproject.toml) ... done
  Created wheel for sent2vec: filename=sent2vec-0.0.0-cp39-cp39-macosx_10_9_x86_64.whl size=147387 sha256=c44542481354218e1045886725003db8fb962b39124040a0c98d9aee475b4b44
  Stored in directory: /private/var/folders/5s/grd6kzt52836tcvqqg_7jx5r0000gn/T/pip-ephem-wheel-cache-75_u2h64/wheels/3c/16/0b/4cc8a8c458bdb5912ce6fce3eb01b776754ed37205953d19f6
Successfully built sent2vec
Installing collected packages: sent2vec
  Attempting uninstall: sent2vec
    Found existing installation: sent2vec 0.0.0
    Uninstalling sent2vec-0.0.0:
      Successfully uninstalled sent2vec-0.0.0
Successfully installed sent2vec-0.0.0
(searchenv) $ python3
Python 3.9.6 (default, Aug 18 2021, 12:38:10) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sent2vec
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/sent2vec.pyx", line 17, in init sent2vec
    cnp.import_array()
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
>>>
