### ISSUE TITLE
Question: when you specify limit, does it start with most frequently found words?

### ISSUE THREAD

**Issue by Shane-Neeley** [ncbi-nlp/BioSentVec#23]
When you load it like this, will these be the top 4E5 words found during training? I believe other vector bins like Google News work like this. Thank you!

```
word2vec = gensim.models.KeyedVectors.load_word2vec_format(
                'data/BioWordVec_PubMed_MIMICIII_d200.vec.bin',
                binary=True,
                limit=int(4E5) # faster load if you limit to most frequent terms?
            )
```

**Comment by qingyu-qc** [comment]
Hi,

I have never used the limit parameter before, but from the documentation yes.

Thanks!

**Comment by Shane-Neeley** [comment]
Yes, tested myself to see words like "the" at the top.

**Comment by qingyu-qc** [comment]
thanks for the confirmation!
