### ISSUE TITLE
Question on calculate the similarity of UMNSRS?

### ISSUE THREAD

**Issue by yikuan8** [ncbi-nlp/BioSentVec#24]
Thank you for the great embedding. I have a few questions on how to calculate the similarity of UMNSRS.

Per my understanding, BioWordVec is a word embedding. Each word is represented to a vector. However, there are some phrases that contain more than one word in UMNSRS. Did you get the average of each word in the phrase and then calculate the cosine similarity?

One more question is how do you deal with the words that are not in the vocabulary? e.g. I found:

(ana)
arthriits
buterfly
varicsoe
haletosis

are not in the vocabulary. Did you impute something or just discard those terms.

One more question is I found the window size in .sh is 30. You describe you were using 20 for extrinsic task. Which one will yield a better result?

Thank you and looking forward to reply!

**Comment by qingyu-qc** [comment]
Hi,

Thanks for using our tool. 

For your first question, yes, a simple averaging method was used following the previous papers.

For the second question,  if you are using BioWordVec model, it can give you a predicted vector if it is an OOV.

Last, we used a window size of 30 for training BioWordVec using PubMed and MIMIC, which mentioned in our paper https://arxiv.org/ftp/arxiv/papers/1810/1810.09302.pdf The preprocessing script reflects that. Another version of BioWordVec only trained using PubMed, used 20 for extrinsic evaluation.

Close for now. Let us know if you have more questions. Thanks!
