### ISSUE TITLE
wiki page - Mention of BioWordVec instead of BioSentVec

### ISSUE THREAD

**Issue by kaushikacharya** [ncbi-nlp/BioSentVec#25]
@qingyu-chen 

https://github.com/ncbi-nlp/BioSentVec/wiki#how-to-use-the-biowordvec-and-biosentvec-model

> The **BioWordVec** is built upon sent2vec.

I guess, you meant to say **BioSentVec**.

**Comment by qingyu-chen** [comment]
Thanks. Fixed.
