### ISSUE TITLE
MedSTS dataset

### ISSUE THREAD

**Issue by coolabhishek** [ncbi-nlp/BioSentVec#26]
Hi

Where can I find the MEDSTS dataset? Also to evaluate the dataset on the BioSentVec model do I need any pre-processing?

Thanks
Abhishek

**Comment by MathewAlexander** [comment]
@coolabhishek 
Hi Abhishek, Did you find the dataset?. If yes, can you tell me where I can find it?

**Comment by jacklxc** [comment]
I cannot find the download link anywhere.

**Comment by coolabhishek** [comment]
https://n2c2.dbmi.hms.harvard.edu/track1

Try to ask here.

**Comment by jacklxc** [comment]
@coolabhishek Thank you!

**Comment by jacklxc** [comment]
The open task does not accept new registration anymore. I am contacting the original author to see if they are willing to share the dataset.

**Comment by coolabhishek** [comment]
https://portal.dbmi.hms.harvard.edu/projects/n2c2-2019-t1/

create a login. 
then click. 
Need help? Contact us!

**Comment by coolabhishek** [comment]
the email will go to the right person. who will reach out to you with a form to be signed by your PI and then they will release the dataset

**Comment by MathewAlexander** [comment]
Yeah, I've sent a mail to Dr. Wang. But unfortunately, as I am not an academic researcher I don't have a PI to sign the agreement. So I am trying to get the CORD19STS dataset now.

**Comment by jacklxc** [comment]
I contacted the author of CORD19STS. He said they don't have the dataset because the data collection was not ideal. Of course, the paper is not officially published.

**Comment by xyz321123** [comment]
Is there any news about the MEDSTS data set? I also want this dataset, I will be very grateful if there is a reply.

**Comment by avinashok** [comment]
@MathewAlexander or anyone above - did you manage to get MedSTS dataset? Is the CORD19STS dataset mentioned same as [this](https://www.kaggle.com/datasets/allen-institute-for-ai/CORD-19-research-challenge)? Looking for a dataset to benchmark clinical domain texts - any suggestions around other similar datasets are appreciated.

**Comment by ZRH0308** [comment]
Anyone above manage to get MedSTS dataset?

**Comment by sebastian-villanue** [comment]
This is an old thread but has anybody been able to get a hold of the MedSTS dataset ?
