### ISSUE TITLE
"Model file cannot be opened for loading!" for BioSentVec

### ISSUE THREAD

**Issue by VPetukhov** [ncbi-nlp/BioSentVec#30]
I have Python 3.8.5 and installed fasttext, as well as sent2vec. But when I try to load the model, python crashes with a single message "Model file cannot be opened for loading!". Full installation code is:
```bash
conda create -n sent2vec "python==3.8.5"
conda activate sent2vec
pip install Cython
git clone https://github.com/facebookresearch/fastText.git
git clone https://github.com/epfml/sent2vec.git
cd fastText
pip install .
cd ../sent2vec
pip install .
```

Then, python code is:

```python
import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model("./BioSentVec_PubMed_MIMICIII-bigram_d700.bin")
```

What could be wrong?

**Comment by qingyu-qc** [comment]
Hey,

I just tested locally and it runs properly with Python 3.8. Please check
whether your model path is correct.

Thanks!

**Comment by VPetukhov** [comment]
Thanks so much for the quick answer! Indeed, the problem was in the model path. I used relative path from the home folder (`"~/.../BioSentVec_PubMed_MIMICIII-bigram_d700.bin"`), but when I replace it with the absolute path (`"/home/.../BioSentVec_PubMed_MIMICIII-bigram_d700.bin"`) it works fine.
