### ISSUE TITLE
Links to vec/model file wrong?

### ISSUE THREAD

**Issue by deakkon** [ncbi-nlp/BioSentVec#4]
Hi, 

thank you for sharing this with the rest of us! Its already coming in handy ;) 

Just a minor issue (and not sure if it is one); did you by mistake link the "opposite" files to respective links:

BioWordVec vector 13GB (200dim, trained on PubMed+MIMIC-III, word2vec bin format) -> downloads the bin file, size 27GB

BioWordVec model 26GB (200dim, trained on PubMed+MIMIC-III) -> downloadds the vec.bin file, size 13GBs. 

Best,
J.

**Comment by qingyu-qc** [comment]
Hello,

Thank you for your interests and pointing out the problems of the links. We have just updated the links.

Best,
QC
