### ISSUE TITLE
Make source corpora available

### ISSUE THREAD

**Issue by craigpfeifer** [ncbi-nlp/BioSentVec#5]
Would it be possible for you to make your source corpora available (both raw & preprocessed (tokenized / sentence split)? Would be very useful in helping folks create resources with other methods.

**Comment by yfpeng** [comment]
We cannot provide you with the corpora due to the copyrights. Instead, we can add the preprocessing methods in the repository, though they are straightforward: `sent_tokenzie` from NLTK + lowercase.

**Comment by craigpfeifer** [comment]
Understood. The preprocessing scripts are always useful!

**Comment by yfpeng** [comment]
Please see #6.
