### ISSUE TITLE
find similar sentences

### ISSUE THREAD

**Issue by arianpasquali** [ncbi-nlp/BioSentVec#7]
Would be possible to find similar sentences using the sent2vec model?
How to use the BioSentVec model to query for similar sentences?

**Comment by yfpeng** [comment]
It is not possible to find similar sentences using either sent2vec or BioSentVec. Instead, BioSentVec can measure how similar two given sentences are.

**Comment by lefft** [comment]
If the embeddings are in one of the standard word2vec formats (C binary or plain text), couldn't they just be loaded as a [`gensim.models.KeyedVectors`](https://radimrehurek.com/gensim/models/keyedvectors.html) instance? If so, then one could query sentences by calling the `.most_similar()` method with kwarg `positive='the sentence to query'`. Haven't actually tried this, but as long as the keys of the vectors are the actual sentences themselves and they're stored in one of the standard word2vec formats, I would think that it should work fine?

**Comment by yfpeng** [comment]
The word embeddings (BioWordVec) are in the standard word2vec format. One could query **words** by calling the `KeyedVectors`. The sentence embeddings are in the `sent2vec` format, **NOT** in the word2vec format. One could use the following code to get the sentence embeddings.

```python
import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model('BioSentVec_PubMed_MIMICIII-bigram_d700.bin')
emb = model.embed_sentence("once upon a time .") 
embs = model.embed_sentences(["first sentence .", "another sentence"]) 
```

**Comment by qingyu-qc** [comment]
> If the embeddings are in one of the standard word2vec formats (C binary or plain text), couldn't they just be loaded as a [`gensim.models.KeyedVectors`](https://radimrehurek.com/gensim/models/keyedvectors.html) instance? If so, then one could query sentences by calling the `.most_similar()` method with kwarg `positive='the sentence to query'`. Haven't actually tried this, but as long as the keys of the vectors are the actual sentences themselves and they're stored in one of the standard word2vec formats, I would think that it should work fine?

Hi,

To my knowledge, Gensim will support sent2vec in a later version https://github.com/RaRe-Technologies/gensim/issues/1376

In the meantime, you could use the in-built functions provided by sent2vec (https://github.com/epfml/sent2vec#using-sentence-level-nearest-neighbour-search-and-analogies). Given a sentence, it can output top k most similar sentence in the corpus.

**Comment by qingyu-qc** [comment]
Close for now. Let us know if you have more questions
