### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc Aborted (core dumped)

### ISSUE THREAD

**Issue by patilaum** [ncbi-nlp/BioSentVec#9]
is this the RAM, GPU-memory or Hard disk memory issue?

**Comment by qingyu-qc** [comment]
Answered your question in another thread. Close for now. Let us know if you have other problems.

**Comment by iCHAIT** [comment]
@qingyu-qc  which thread are you referring to? I am having the same issue.

**Comment by iCHAIT** [comment]
@patilaum were you able to resolve this?
